spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/${AUTH_DB_NAME:vidops_auth}
    username: ${AUTH_DB_USER:vidops}
    password: ${AUTH_DB_PASSWORD:enis1234}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

vidops:
  auth:
    cookie:
      secure: false   # https yoksa false; reverse proxy ile https'e geçince true yaparsın
      same-site: Lax
