apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: vidops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: vidops/auth-service:0.1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: AUTH_DB_URL
              value: "jdbc:postgresql://postgres-auth:5432/vidops_auth"
            - name: AUTH_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: username
            - name: AUTH_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: password
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                configMapKeyRef:
                  name: vidops-config
                  key: KAFKA_BOOTSTRAP
            - name: JWT_SECRET_BASE64
              valueFrom:
                secretKeyRef:
                  name: vidops-secrets
                  key: JWT_SECRET_BASE64
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: vidops-secrets
                  key: JWT_ISSUER
            - name: ACCESS_TOKEN_TTL_MIN
              valueFrom:
                configMapKeyRef:
                  name: vidops-config
                  key: ACCESS_TOKEN_TTL_MIN
            - name: REFRESH_TOKEN_TTL_DAYS
              valueFrom:
                configMapKeyRef:
                  name: vidops-config
                  key: REFRESH_TOKEN_TTL_DAYS
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vidops
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
